export C_INCLUDE_PATH=/usr/include/freetype2
export CPLUS_INCLUDE_PATH=/usr/include/freetype2
export LANG=zh_CN.GBK

g++ -o demo demo.cpp -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc
g++ -o demo2 demo2.cpp CvxText.cpp -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lfreetype
